Новая ветка Feature/1
WhatTheAncient/CPP pull request #2
Opened 2021-03-08 14:48 UTC by WhatTheAncient

Разработана программа выполняющая требования issue. Есть вопрос по поводу функции .del_even_numbers(). Хотелось бы всё-таки сделать так, чтобы она не выводила новый массив на экран, а возвращала новый массив и его размерность. Но я не смог этого реализовать.

2021-03-09 11:52 UTC, Const-Phi reviewed
Частично прорецензировал. Общий вывод &ndash; стоит поработать над стилистикой.

@MarinaPaley, дорецензируй, пожалуйста, по существу `¯\_(ツ)_/¯`

2021-03-09 11:52 UTC, Const-Phi commented on Source.cpp
> +	arr = new int[size];
Важный момент &ndash; тип [`int`](https://en.cppreference.com/w/cpp/language/types#Integer_types) допускает возможность хранения _отрицательного_ значения. Выделить память в `-2` элемента типа `int`, кажется невозможным.

Я бы для этой цели использовал бы тип [`size_t`](https://en.cppreference.com/w/c/types/size_t):
```cpp
int * array_keyboard_filling(const size_t array_size)
{
    // ...
}
```

Также я хотел бы обратить внимание на то, что разделение объяевления и определения переменной в данном случае не кажется оправданным:
```cpp
   auto array = new int[array_size];
```

2021-03-09 11:52 UTC, Const-Phi commented on Source.cpp
>  		cout << "Enter array element ";
Я бы вынес это сообщение в качестве параметра метода, например, как-то так:
```cpp
int * array_keyboard_filling(const size_t array_size, const string& message)
{
    // ...
}
```

2021-03-09 11:52 UTC, Const-Phi commented on Source.cpp
>  		arr[i] = rand() % 31 - 10;
[Волшебные константы](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)) в коде &ndash; не самый лучший выбор.

2021-03-09 11:52 UTC, Const-Phi commented on Source.cpp
>  	srand(time(NULL));
Я бы изменил стилистику данного вызова, с учётом [примера](https://en.cppreference.com/w/cpp/numeric/random/srand), а также посмотрел бы в сторону [`<random>`](https://www.cplusplus.com/reference/random/) (важно помнить, что это появилось в [C++11](https://ru.wikipedia.org/wiki/C++11)). Примеры использования `<random>` можно посмотреть например [здесь](https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution). Также на SO [цитируют](https://stackoverflow.com/a/20016865/2761685) книгу [Страуструпа](https://ru.wikipedia.org/wiki/Страуструп,_Бьёрн).

2021-03-10 06:03 UTC, MarinaPaley requested changes
Согласна с комментариями К.М.

2021-03-16 09:10 UTC, WhatTheAncient commented on Source.cpp
>  	srand(time(NULL));
`int* array_random_filling(const size_t array_size) {
	random_device rd;
	mt19937 gen(rd());
	uniform_int_distribution <> dis(-10, 20);
	auto arr = new int[array_size];
	for (int i = 0; i < array_size; i++) {
		arr[i] = dis(gen);
	};
	return arr;
};`
Сделал с помощью <random>

2021-03-16 09:13 UTC, WhatTheAncient commented on Source.cpp
>  		arr[i] = rand() % 31 - 10;
```	int rand_min = -10, rand_max = 20;
	uniform_int_distribution <> dis(rand_min, rand_max);
	auto arr = new int[array_size];
	for (int i = 0; i < array_size; i++) {
		arr[i] = dis(gen);
```

2021-03-16 09:14 UTC, WhatTheAncient commented on Source.cpp
>  	srand(time(NULL));
Переделал с использованием <random>

2021-03-16 09:16 UTC, WhatTheAncient commented on Source.cpp
> +	arr = new int[size];
int* array_keyboard_filling(const size_t array_size, const string& message) 
{
	auto arr = new int[array_size];
        ...
};

2021-06-30 10:47 UTC, closed without merging