Разработана программа
WhatTheAncient/CPP pull request #4
Opened 2021-03-18 10:05 UTC by WhatTheAncient

2021-03-19 20:58 UTC, MarinaPaley requested changes
Стоит учесть замечания.

Ко всему прочему стоит отметить, что во всех функциях, которые не предусматривают изменения массива, стоит указатель на этот массив снабдить модификатором `const`, чтобы предоставить соответсвующие гарантии.

2021-03-19 20:58 UTC, MarinaPaley commented on Source_1.cpp
> +};
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) придирки про именование из предыдущего коментария усиливаются замечанием по делу.

А именно, локальные даже не переменные, а константы &ndash; `rand_min` и `rand_max` стоило бы вынести в качестве аргуметов функции (пусть и со значениями по умолчанию):
```cpp
int* array_random_filling(const size_t size, const int min = -10, const int max = 20) {
    // ...
}
```

Также в качестве придирки `dis` &ndash; это всё же `distribution`, а `gen`  &ndash; это `generator`.

**P.S.** `filling` &ndash; всё же _заполнение_, а не _заполнить_ (`fill`).

И совсем на последок &ndash; точку с запятой после тела функции ставить не обязательно.

2021-03-19 20:58 UTC, MarinaPaley commented on Source_1.cpp
> +};
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) `destroyer` &ndash; _существительное_ (разрушитель), а не _глагол_.

По существу, стоит отметить, что в общем случае никто не гарантирует, что `arr` указывает на неразрушенный объект. Стоит добавить проверку, например такую:
```cpp
void array_destroyer(int* array)
{
    if (array != nullptr)
    {
        delete[] array;
        array = nullptr;
    }
}
```

2021-03-19 20:58 UTC, MarinaPaley commented on Source_1.cpp
> +};
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) продолжам традицию предыдущих комментариев, посвящённых проблемам именования:
  - `s` &ndash; это сумма, то есть `sum` или `summa`.

Для меня осталось не ясным с какой целью Вы итерируете массив с конца &ndash; в чём выигрыш, ведь от перемены мест слагаемых сумма не меняется?

**Про ошибки**
  - `break` избыточен и ломает логику &ndash; посчитайте руками те же данные, что генерирует Ваша программа и сравните с результатом данной функции;
  - что мешало итерировать с шагом `2`, а не проверять подходит или нет тот или иной индекс;
  - [_&laquo;Уж сколько раз твердили миру...&raquo;_](https://sites.middlebury.edu/russianshortstories/поэзия/и-а-крылов/ворона-и-лисица/) что не стоит _втыкать_ взаимодействие с пользователем в функцию без вящей на то необходимости &ndash; вот скажите, зачем Вам тут `cout`? Правильнее было бы изменить тип возвращаемого значения.

2021-03-19 20:58 UTC, MarinaPaley commented on Source_1.cpp
> +};
**Про ошибки**
`cout`/`cin` &ndash; избыточны. `local_max` стоило бы получать как аргумент фунции, а `count_of_elements` возвращать из функции. 

**Про типизацию**
По смыслу `count_of_elements` &ndash; скорее `size_t`, а не `int`. Разве количесво бывает отрицательным?

2021-03-19 20:58 UTC, MarinaPaley commented on Source_1.cpp
> +	};
[Nit:](https://google.github.io/eng-practices/review/reviewer/standard.html) избыточная `;`

2021-03-21 16:28 UTC, Const-Phi requested changes
Стоит исправить замечания.

По общей канве программы
  1. Стоит добавить документацию, используя, например, [Doxygen](https://ru.wikipedia.org/wiki/Doxygen). Почитать можно, например, на [хабре](https://habr.com/ru/post/252101/).  Сама студия умеет генерировать документацию:
  ![image](https://user-images.githubusercontent.com/8349213/111912210-ba86bb80-8a79-11eb-8e39-c003ae56172b.png)
  2. Стоит вынести объявления функций до `main`, а реализацию &ndash; после. Пример, можно посмотреть [здесь](https://www.studytonight.com/cpp/functions-in-cpp.php).

2021-03-21 16:28 UTC, Const-Phi commented on Source_1.cpp
> +	};
Я бы для этой цели использовал [`enum`](https://en.cppreference.com/w/cpp/language/enum)  и [`switch`](https://en.cppreference.com/w/cpp/language/switch).  Например, как-то так:
```cpp
/**
 * \brief Перечисление поставщиков данных для формирования массива.
 */
enum class array_data_producers
{
    /**
     * \brief Получение данных от пользователя посредством ввода с клавиатуры.
     */
    keyboard = 1,

    /**
     * \brief Получение данных посредством применения генератора псевдо-случайных чисел.
     */
    random = 2,
};
```

Обращаю Ваше внимание на то, что используется форма [`enum class`](https://docs.microsoft.com/en-us/cpp/cpp/enumerations-cpp?view=msvc-160) вместо `enum`, что [_является более предпочтительным_](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums). Данный подход вносит некоторые особенности в использование таким образом описанного `enum`-а, например, такой подход запрещает неявное приведение типа `enum` &rarr; `int`. В коде это выражается через использование [`static_cast`](https://en.cppreference.com/w/cpp/language/static_cast):

```cpp
array_data_producers read_choice()
{
    cout << "Выберите способ заполнения массива.\n"
        << static_cast<int>(array_data_producers::keyboard) << " - пользовательский ввод данных при помощи клавиатуры;\n"
        << static_cast<int>(array_data_producers::random) << " - получение данных от генератора псевдо-случайных чисел.\n"
        << "Способ = ";

    auto raw_choice = 0;
    cin >> raw_choice;

    return static_cast<array_data_producers>(raw_choice);
}
```

2021-05-26 15:09 UTC, MarinaPaley approved these changes

2021-05-26 15:09 UTC, MarinaPaley commented on Project_1 (4-2-3)/Source.cpp
> +{
```cpp
if (array == nullptr)
    return;
delete[] array;
array = nullptr;

2021-06-30 10:44 UTC, closed without merging